export const UPGRADES = [
  {
    key: 'slow',
    label: 'Slow Bubbles',
    icon: 'turtle',
    description: 'Bubbles cross 15% slower per level — easier to catch',
    maxLevel: 5,
    costs: [180, 520, 1450, 3900, 9800],
  },
  {
    key: 'boost',
    label: 'Pearl Luster',
    icon: 'star',
    description: '+50% pearls per pop per level',
    maxLevel: 4,
    costs: [260, 760, 2100, 5600],
  },
  {
    key: 'magnet',
    label: 'Bubble Magnet',
    icon: 'magnet',
    description: 'Hover radius grows 12 px per level — pop from further away',
    maxLevel: 5,
    costs: [220, 640, 1780, 4700, 11800],
  },
  {
    key: 'auto',
    label: 'Auto Popper',
    icon: 'bot',
    description: 'Auto-pops 1 extra bubble per second per level',
    maxLevel: 3,
    costs: [900, 3200, 11800],
  },
  {
    key: 'factory',
    label: 'Slow Spawns',
    icon: 'hourglass',
    description: 'Adds 150 ms to bubble spawn interval per level',
    maxLevel: 5,
    costs: [200, 560, 1520, 4100, 10400],
  },
  {
    key: 'lives',
    label: 'Extra Life',
    icon: 'heart',
    description: 'Start each game with 1 extra life',
    maxLevel: 3,
    costs: [650, 2100, 7200],
  },
];
